"""Constants for Georgia Water Quality System."""

# Georgia Counties (from the official website)
GEORGIA_COUNTIES = [
    "All",
    "APPLING",
    "ATKINSON",
    "BACON",
    "BAKER",
    "BALDWIN",
    "BANKS",
    "BARROW",
    "BARTOW",
    "BEN HILL",
    "BERRIEN",
    "BIBB",
    "BLECKLEY",
    "BRANTLEY",
    "BROOKS",
    "BRYAN",
    "BULLOCH",
    "BURKE",
    "BUTTS",
    "CALHOUN",
    "CAMDEN",
    "CAMPBELL",
    "CANDLER",
    "CARROLL",
    "CATOOSA",
    "CHARLTON",
    "CHATHAM",
    "CHATTAHOOCHEE",
    "CHATTOOGA",
    "CHEROKEE",
    "CLARKE",
    "CLAY",
    "CLAYTON",
    "CLINCH",
    "COBB",
    "COFFEE",
    "COLQUITT",
    "COLUMBIA",
    "COOK",
    "COWETA",
    "CRAWFORD",
    "CRISP",
    "DADE",
    "DAWSON",
    "DECATUR",
    "DEKALB",
    "DODGE",
    "DOOLY",
    "DOUGHERTY",
    "DOUGLAS",
    "EARLY",
    "ECHOLS",
    "EFFINGHAM",
    "ELBERT",
    "EMANUEL",
    "EVANS",
    "FANNIN",
    "FAYETTE",
    "FLOYD",
    "FORSYTH",
    "FRANKLIN",
    "FULTON",
    "GILMER",
    "GLASCOCK",
    "GLYNN",
    "GORDON",
    "GRADY",
    "GREENE",
    "GWINNETT",
    "HABERSHAM",
    "HALL",
    "HANCOCK",
    "HARALSON",
    "HARRIS",
    "HART",
    "HEARD",
    "HENRY",
    "HOUSTON",
    "IRWIN",
    "JACKSON",
    "JASPER",
    "JEFF DAVIS",
    "JEFFERSON",
    "JENKINS",
    "JOHNSON",
    "JONES",
    "LAMAR",
    "LANIER",
    "LAURENS",
    "LEE",
    "LIBERTY",
    "LINCOLN",
    "LONG",
    "LOWNDES",
    "LUMPKIN",
    "MACON",
    "MADISON",
    "MARION",
    "MCDUFFIE",
    "MCINTOSH",
    "MERIWETHER",
    "MILLER",
    "MILTON",
    "MITCHELL",
    "MONROE",
    "MONTGOMERY",
    "MORGAN",
    "MURRAY",
    "MUSCOGEE",
    "NEWTON",
    "OCONEE",
    "OGLETHORPE",
    "PAULDING",
    "PEACH",
    "PICKENS",
    "PIERCE",
    "PIKE",
    "POLK",
    "PULASKI",
    "PUTNAM",
    "QUITMAN",
    "RABUN",
    "RANDOLPH",
    "RICHMOND",
    "ROCKDALE",
    "SCHLEY",
    "SCREVEN",
    "SEMINOLE",
    "SPALDING",
    "STEPHENS",
    "STEWART",
    "SUMTER",
    "TALBOT",
    "TALIAFERRO",
    "TATTNALL",
    "TAYLOR",
    "TELFAIR",
    "TERRELL",
    "THOMAS",
    "TIFT",
    "TOOMBS",
    "TOWNS",
    "TREUTLEN",
    "TROUP",
    "TURNER",
    "TWIGGS",
    "UNION",
    "UPSON",
    "WALKER",
    "WALTON",
    "WARE",
    "WARREN",
    "WASHINGTON",
    "WAYNE",
    "WEBSTER",
    "WHEELER",
    "WHITE",
    "WHITFIELD",
    "WILCOX",
    "WILKES",
    "WILKINSON",
    "WORTH",
]

# Water System Types (from official website)
WATER_SYSTEM_TYPES = [
    {"value": "All", "label": "All", "code": None},
    {"value": "C", "label": "Community", "code": "CWS"},
    {"value": "NC", "label": "Non-Community", "code": "TNCWS"},
    {"value": "NTNC", "label": "Non-Transient Non-Community", "code": "NTNCWS"},
]

# Primary Source Water Types (from official website)
PRIMARY_SOURCE_WATER_TYPES = [
    {"value": "All", "label": "All", "code": None},
    {"value": "GW", "label": "GroundWater", "code": "GW"},
    {"value": "GWP", "label": "GroundWater Purchased", "code": "GWP"},
    {"value": "GU", "label": "GroundWater UDI SurfaceWater", "code": "GU"},
    {"value": "GUP", "label": "GroundWater UDI SurfaceWater Purchased", "code": "GUP"},
    {"value": "SW", "label": "SurfaceWater", "code": "SW"},
    {"value": "SWP", "label": "SurfaceWater Purchased", "code": "SWP"},
]

# Point of Contact Types (from official website)
POINT_OF_CONTACT_TYPES = [
    {"value": "None", "label": "None", "code": None},
    {"value": "AC", "label": "Administrative Contact", "code": "AC"},
    {"value": "EC", "label": "Emergency Contact", "code": "EC"},
    {"value": "OW", "label": "Owner", "code": "OW"},
    {"value": "LE", "label": "Lead Engineer", "code": "LE"},
    {"value": "OP", "label": "Operator", "code": "OP"},
    {"value": "FC", "label": "Financial Contact", "code": "FC"},
    {"value": "LC", "label": "Legal Contact", "code": "LC"},
    {"value": "DO", "label": "Designated Op in Charge", "code": "DO"},
    {"value": "SA", "label": "Sampling", "code": "SA"},
]

# Sample Classes (from official website)
SAMPLE_CLASSES = [
    {"value": "null", "label": "Click to select a value...", "code": None},
    {
        "value": "ColiformSample",
        "label": "Coliform/Microbial Samples",
        "code": "COLIFORM",
    },
    {
        "value": "ColiformSampleDetection",
        "label": "Coliform/Microbial Samples Detection Only",
        "code": "COLIFORM_DETECT",
    },
    {
        "value": "ColiformSummaries",
        "label": "Coliform Summaries",
        "code": "COLIFORM_SUMMARY",
    },
    {
        "value": "LeadandCopperSummaries",
        "label": "Lead and Copper Summaries",
        "code": "LEAD_COPPER",
    },
    {
        "value": "SummarizedFieldSampleResults",
        "label": "Summarized Field Sample Results",
        "code": "FIELD_SUMMARY",
    },
    {"value": "NonTCRAll", "label": "Chem/Rad Samples All", "code": "CHEM_RAD_ALL"},
    {"value": "NonTCRAnalyte", "label": "Samples by Analyte", "code": "BY_ANALYTE"},
    {
        "value": "NonTCRDetection",
        "label": "Chem/Rad Samples Detection Only",
        "code": "CHEM_RAD_DETECT",
    },
]

# Search actions (from official website)
SEARCH_ACTIONS = [
    "Search For Water Systems",
    "Search For Samples",
    "Schedule Lookup and Sampling Points Download",
    "Review Consumer Confidence Data",
]

# Database field mappings
DB_FIELD_MAPPINGS = {
    "system_types": {"C": "CWS", "NC": "TNCWS", "NTNC": "NTNCWS"},
    "source_water_codes": {
        "GW": "GW",
        "GWP": "GWP",
        "GU": "GU",
        "GUP": "GUP",
        "SW": "SW",
        "SWP": "SWP",
    },
    "sample_contaminants": {
        "ColiformSample": "COL%",
        "ColiformSampleDetection": "COL%",
        "ColiformSummaries": "COL%",
        "LeadandCopperSummaries": ["PB90", "CU90"],
        "NonTCRAll": "CHEM_RAD",
        "NonTCRAnalyte": "BY_ANALYTE",
        "NonTCRDetection": "CHEM_RAD",
    },
}

# Friendly display names
FRIENDLY_NAMES = {
    "system_types": {
        "CWS": "Community Water System",
        "TNCWS": "Transient Non-Community Water System",
        "NTNCWS": "Non-Transient Non-Community Water System",
    },
    "source_water": {
        "GW": "Groundwater",
        "GWP": "Groundwater (Purchased)",
        "GU": "Groundwater/Surface Water Mix",
        "GUP": "Groundwater/Surface Water Mix (Purchased)",
        "SW": "Surface Water",
        "SWP": "Surface Water (Purchased)",
    },
}
